version: '3.0'

services:
  api:
    build: .
    container_name: api
    hostname: api
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mysql:5.7.26
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: notable
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    container_name: db
    hostname: db
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d/
  adminer:
    image: adminer
    ports:
      - 8080:8080
    container_name: adminer
    depends_on:
      - db
